// export const SEARCH_BY_VIN_START = 'SEARCH_BY_VIN_START';
export const SEARCH_BY_VIN_SUCCESS = 'SEARCH_BY_VIN_SUCCESS';
export const SECOND_SEARCH_BY_VIN = 'SECOND_SEARCH_BY_VIN';
export const SEARCH_DETAIL = 'SEARCH_DETAIL';